### ISSUE TITLE
[question] content warnings

### ISSUE THREAD

**Issue by MimzyFang** [Rengyr/Vulpes-Porto#1]
Is it possible to add a CW to a post that the bot post's?

**Comment by Rengyr** [comment]
At the moment it's not implemented, but the mastodon API supports it and it can be added if you want that feature.

**Comment by Rengyr** [comment]
Feature implemented. Adding "content_warning" to the image in json file will post the image with content warning. (see example in readme)

**Comment by MimzyFang** [comment]
Thank you
