### ISSUE TITLE
Specify max log levels in the config

### ISSUE THREAD

**Issue by kouya** [Rengyr/Vulpes-Porto#2]
To dial down the log noise a bit in production, we could add a log level to the config json. Example:

`"log_level": "err"`

Will only log errors and higher severity and discard the rest.

**Comment by Rengyr** [comment]
Implemented in 57572a93666500b3df4c81b8c744ae4723bf9fd5, e26c9c7696d8de6616d34f0e3a2d3e6d1ae9e990
